package gravity

var (
	EndpointRoot = "https://api.gravity.place/gravity/"

	EndpointCommon = EndpointRoot + "common/"
	EndpointUser   = EndpointRoot + "user/"

	EndpointRegisterType                       = EndpointCommon + "registerFaq"
	EndpointSendMessage                        = EndpointCommon + "sendMessage"
	EndpointSystemUpgrade                      = EndpointCommon + "systemUpgrade"
	EdnpotinGetImpornWord                      = EndpointCommon + "getimpornword"
	EndpointUploadVoiceChatInfo                = EndpointCommon + "uploadVoiceChatInfo"
	EndpointUploadLog                          = EndpointCommon + "uploadLog"
	EndpointUploadCheck                        = EndpointCommon + "uploadCheck"
	EndpointUploadChunk                        = EndpointCommon + "uploadChunk"
	EndpointNewUploadV2                        = EndpointCommon + "newUploadV2"
	EndpointAppeal                             = EndpointCommon + "appeal"
	EndpointQrcode                             = EndpointCommon + "qrcode"
	EndpointGetUserCountryFunctionSwitchConfig = EndpointCommon + "getUserCountryFunctionSwitchConfig"

	EndpointVirtual3DStatusDiaryList     = EndpointUser + "virtual3DStatusDiaryList"
	EndpointVirtual3DEmojiConfigList     = EndpointUser + "virtual3DEmojiConfigList"
	EndpointVirtual3DPropStatusForSquare = EndpointUser + "virtual3DPropStatusForSquare"
	EndpointVirtual3DReceiveRewards      = EndpointUser + "virtual3DReceiveRewards"
	EndpointVirtual3DShortInfoList       = EndpointUser + "virtual3DShortInfoList"
	EndpointUserListInfo                 = EndpointUser + "userListInfo"
	EndpointUpdateSeeking                = EndpointUser + "updateSeeking"
	EndpointCheckCode                    = EndpointUser + "checkCode"
	EndpointGetSeeking                   = EndpointUser + "getSeeking"
	EndpointHofUserList                  = EndpointUser + "HofUserList"
	EndpointThirdLogin                   = EndpointUser + "third/login"
	EndpointBindEmail                    = EndpointUser + "email/bindEmail"
	EndpointBindCode                     = EndpointUser + "bindCode"
	EndpointCheckInstall                 = EndpointUser + "checkInstall"
	EndpointCheckRegister                = EndpointUser + "checkRegister"
	EndpointEmailIsBind                  = EndpointUser + "email/isbind"
	EndpointEmailIsRegistered            = EndpointUser + "email/isreg"
	EndpointInterestClassify             = EndpointUser + "interestClassify"
	EndpointEmailLogin                   = EndpointUser + "email/login"
	EndpointLoginWithCode                = EndpointUser + "loginWithCode"
	EndpointMobileIsRegistered           = EndpointUser + "mobile/isreg"
	EndpointEmailSendMsg                 = EndpointUser + "email/sendmsg"
	EndpointAccountLogOffMsg             = EndpointUser + "account/logOffMsg"
	EndpointAccountLogOff                = EndpointUser + "account/logOff"
	EndpointIsRaisePopup                 = EndpointUser + "isRaisePopup"
	EndpointUpdateDevice                 = EndpointUser + "updateDevice"
	EndpointUpdateSetting                = EndpointUser + "updateSetting"
	EndpointGetUserShareSetting          = EndpointUser + "getUserShareSetting"
	EndpointGetCenterBackground          = EndpointUser + "getCenterBackground"
	EndpointUpdateMicrophoneColor        = EndpointUser + "updateMicrophoneColor"
	EndpointGetMicrophoneColor           = EndpointUser + "getMicrophoneColor"
	EndpointGetEntryEffects              = EndpointUser + "getEntryEffects"
	EndpointGetProfileCardDecorationList = EndpointUser + "getProfileCardDecorationList"
	EndpointGetFeedPendantList           = EndpointUser + "getFeedPendantList"
	EndpointUpdateCenterBackground       = EndpointUser + "updateCenterBackground"
	EndpointUpdateEntryEffects           = EndpointUser + "updateEntryEffects"
	EndpointUpdateProfileCardDecoration  = EndpointUser + "updateProfileCardDecoration"
	EndpointUpdateFeedPendant            = EndpointUser + "updateFeedPendant"
	EndpointPortraitListCount            = EndpointUser + "portraitListCount"
	EndpointUpdateTag                    = EndpointUser + "updateTag"
	EndpointUpdateUserInfo               = EndpointUser + "updateUserInfo"
	EndpointSecondHomePage               = EndpointUser + "secondHomePage"
	EndpointUpdateSnsInfo                = EndpointUser + "updateSnsInfo"
	EndpointExtraInfo                    = EndpointUser + "extraInfo"
	EndpointGetInterestTag               = EndpointUser + "getInterestTag"
	EndpointDressUpCenter                = EndpointUser + "dressUpCenter"
	EndpointUserInfoCenter               = EndpointUser + "userInfoCenter"
	EndpointUserDetail                   = EndpointUser + "detail"
	EndpointSettingCenter                = EndpointUser + "settingCenter"
	EndpointWhiteListCheck               = EndpointUser + "whiteListCheck"
)
